// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeo3gv_uzh-czdD57YcA9VUIHT1rRjOjI',
    appId: '1:581503837706:web:73c4906269e9c9e2b2a1f3',
    messagingSenderId: '581503837706',
    projectId: 'exercicioavaliacao2-15b51',
    authDomain: 'exercicioavaliacao2-15b51.firebaseapp.com',
    storageBucket: 'exercicioavaliacao2-15b51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQurCgsceR374VZn2zBFXeaDFAxaHWmcs',
    appId: '1:581503837706:android:0bcfe77211ca910eb2a1f3',
    messagingSenderId: '581503837706',
    projectId: 'exercicioavaliacao2-15b51',
    storageBucket: 'exercicioavaliacao2-15b51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBYagtsGrT0ourqORT4iqYkZnDSUi_iCE',
    appId: '1:581503837706:ios:1d7f34ec9f4d6595b2a1f3',
    messagingSenderId: '581503837706',
    projectId: 'exercicioavaliacao2-15b51',
    storageBucket: 'exercicioavaliacao2-15b51.firebasestorage.app',
    iosBundleId: 'com.example.exercicioavaliacao2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBYagtsGrT0ourqORT4iqYkZnDSUi_iCE',
    appId: '1:581503837706:ios:1d7f34ec9f4d6595b2a1f3',
    messagingSenderId: '581503837706',
    projectId: 'exercicioavaliacao2-15b51',
    storageBucket: 'exercicioavaliacao2-15b51.firebasestorage.app',
    iosBundleId: 'com.example.exercicioavaliacao2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeo3gv_uzh-czdD57YcA9VUIHT1rRjOjI',
    appId: '1:581503837706:web:2b19c6f3384df323b2a1f3',
    messagingSenderId: '581503837706',
    projectId: 'exercicioavaliacao2-15b51',
    authDomain: 'exercicioavaliacao2-15b51.firebaseapp.com',
    storageBucket: 'exercicioavaliacao2-15b51.firebasestorage.app',
  );
}
